### ISSUE TITLE
Open leg is missing after deleting the closing trade

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#14]
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/79a1d1a4-faf2-48ce-8035-c257b5a36fdb)

If I delete the closed trade, the open leg no longer appears under active trades.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/26f931fc-b122-4943-80b4-080de6dce3b1)

I have to restart the app first.

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/a9381257-dc1c-4ccf-aa55-d57886e69844)

**Comment by PaulSquires** [comment]
This bug should now be fixed in the latest commit.
