### ISSUE TITLE
TWS cannot be disconnected

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#17]
The connection to the TWS cannot be disconnected when I click on the icon.

**Comment by PaulSquires** [comment]
I will check into this again but I remember long ago attempting to implement a "connect / disconnect / reconnect" type of pattern. IIRC, the Interactive Broker's api breaks the low level socket with some type of exception causing reconnects not to work. When the user clicks on the connect icon but is already connected, I could add a dialog box to ask the user if he wishes to disconnect. I could then simply try to close/restart the program. I will check into all of this again. I do know that if you close your instance of TWS then TradeTracker will disconnect.

One more question, when you do disconnect, what should happen to all of the currently displayed live data that's on the screen that will now be outdated? Should I simply reset it, or just leave it there?

**Comment by Flippo24** [comment]
Try it out again. Perhaps the problem has already been solved by IB at some point. I don't like the user experience of restarting the program. 

If you are working on the connections anyway... I have the following suggestions:
If there is no connection yet, when clicking on the icon a context menu with the selection TWS or Yahoo. 
If there is a connection, ask for confirmation again when you click on the icon.
If a connection has been requested (icon is green) and the connection is disconnected, then re-establish it. Possibly in intervals of 10-60 sec. For up to 5 times, then display an error message. As long as a connection is being established, i.e. when starting or reconnecting, color the symbol yellow. 

Add these parameters to the options menu later. Together with the IP and port number.

**Comment by Flippo24** [comment]
> One more question, when you do disconnect, what should happen to all of the currently displayed live data that's on the screen that will now be outdated? Should I simply reset it, or just leave it there?

I have forgotten this point. I thought it was pretty stupid that I didn't see any data in the tools for the last few days, even though I had a connection to TWS. 

Now you have to ask yourself how you want to deal with it. 
1. display the last traded price? No matter from when it is. Possibly with a time stamp? Maybe highlight it in color if it is from the previous day?
2. determine the current price from the ask and bid for an illiquid position?

I enter the model price for the options in my spreadsheet.

**Comment by PaulSquires** [comment]
> If you are working on the connections anyway... I have the following suggestions: If there is no connection yet, when clicking on the icon a context menu with the selection TWS or Yahoo. If there is a connection, ask for confirmation again to quit the connection when you click on the icon. 

This is implemented now via a popup menu that appears to the right of the Connect icon. The problem of disconnecting and not being able to re-connect is still there but I will work on trying to find a fix for it.

**Comment by Flippo24** [comment]
I'm sure you've already checked this?
[ib-api](https://interactivebrokers.github.io/tws-api/connection.html#broken)

**Comment by Flippo24** [comment]
Maybe this gives you a hint...
[elitetrader](https://www.elitetrader.com/et/threads/handling-disconnects-when-using-the-ib-api.11059/)

**Comment by PaulSquires** [comment]
Thanks! Yes, I saw the IBKR documentation before on disconnected handles. I will read through that elitetrader link also. I am able to recover/re-establish connection if TWS simply loses its connection with their server (internet problem, etc); however, it is re-connecting when TradeTracker disconnects from TWS is my problem. The api throws 2 socket exceptions. I do see them being reported in the "error" handler (see screenshot). I guess I just need to understand how to gracefully recover from those exceptions. It could be a C++ thing that I am not familiar with. I'm sure I'll figure it out.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/09d834d1-d184-4180-a83c-23c064523bbd)

You can see the socket exception errors reported (and also some of my own debug code when I start and terminate a few threads that I created during TradeTracker execution).

**Comment by Flippo24** [comment]
Have you tried connecting with a different connection ID after the connection has been lost? Old ID +1.

**Comment by Flippo24** [comment]
How do you force this error?

**Comment by Flippo24** [comment]
The connection to TWS no longer works in the new version. The symbol shortly turns green and then red again. In the VS output window I find the... The specified service is unknown. The service was not found in the specified namespace.

> onecore\net\netprofiles\service\src\nsp\dll\namespaceserviceprovider.cpp(550)\nlansp_c.dll!00007FFD832CD93D: (caller: 00007FFDBAD2ACF6) LogHr(1) tid(8ca0) 8007277C Der angegebene Dienst ist unbekannt. Der Dienst wurde nicht im angegebenen Namespace gefunden.
Der Thread 0xc640 hat mit Code 0 (0x0) geendet.
Der Thread 0x52c0 hat mit Code 0 (0x0) geendet.
Der Thread 0x4e48 hat mit Code 0 (0x0) geendet.
Der Thread 0x23a8 hat mit Code 0 (0x0) geendet.

**Comment by Flippo24** [comment]
Sorry, it was my mistake. I had another productive version of TradeTracker open. This caused an attempt to open the same ID 0 again.

**Comment by PaulSquires** [comment]
> Have you tried connecting with a different connection ID after the connection has been lost? Old ID +1.

Interesting. I will try that to see if it helps. 👍

**Comment by PaulSquires** [comment]
SUCCESS!!! (I hope) 😀 

I was able to catch the exception in the error callback; set a flag in the client class indicating that the socket had exploded; and check that flag when the user attempts to re-connect where, at that time, the socket and reader classes are destroyed and re-created. I did not have to increment the client id (although I did test that approach prior to finding this solution).

Seems to work okay. Hopefully you find the same success as I have had with it so far.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/4303b5ab-60ea-4c12-9ea0-da992e416131)


![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/3e0d2c33-f356-4eda-ac9a-1ec2f2820ba0)

**Comment by PaulSquires** [comment]
Looks like I should add an additional option to the connect popup menu to allow to connect to TWS using the Paper trading account. I will do that.

**Comment by PaulSquires** [comment]
> Looks like I should add an additional option to the connect popup menu to allow to connect to TWS using the Paper trading account. I will do that.

This is now complete and uploaded into repository. I have tested it with the TWS paper trading account and it appears to work perfectly.

I will close this issue once I get positive confirmation feedback on the new connection and re-connection functionality.

**Comment by Flippo24** [comment]
Sorry, it is not working yet. When I was connected to the TWS, I restarted the TWS via the file menu. The connection was interrupted. After the restart, the app tries to connect. This can be seen under Data in the TWS. The connection is immediately closed again and deleted.

**Comment by PaulSquires** [comment]
Ah, I had not tested the situation when TWS itself is closed down. I tested when the user connects and disconnects with TradeTracker. I also believe TradeTracker handles the situation correctly where TWS is active but loses its internet connection but re-establishes it.

I investigated what happens when TWS closes and it sends a connectionClosed() event rather than an error. I simply respoinded to that event and now everythign appears to working correctly.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/c4147097-cbef-4b7d-b7e1-844a103a900f)

**Comment by Flippo24** [comment]
I can confirm that you can now establish a connection again. Closing the connection manually also works. Good job.

**Comment by PaulSquires** [comment]
That's great news! Thanks for all of your help and suggestions. You have been a TREMENDOUS help to me and I really appreciate it. 😀

**Comment by Flippo24** [comment]
You help me with your tool. So i can give something back to you this way. Even if it's just my wishes. :laughing:
