### ISSUE TITLE
Window opens on a different monitor

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#18]
If the main window is open on a second monitor and the Trade Management window is opened, it opens on the main monitor. Please open the window in the center of the main window. As a workaround, move the window there after opening. Please note this for all windows.

**Comment by PaulSquires** [comment]
Confirmed on my multi-monitor setup also. I will fix and report back when the code is corrected.

**Comment by PaulSquires** [comment]
Implemented a monitor aware centering function AfxCenterWindowMonitorAware() so hopefully all popup windows will now display on the correct monitor.

**Comment by Flippo24** [comment]
Works as expected. Thank you.
