### ISSUE TITLE
Add FIFO Method

### ISSUE THREAD

**Issue by PaulSquires** [PaulSquires/TradeTracker#20]
### Discussed in https://github.com/PaulSquires/TradeTracker/discussions/12

<div type='discussions-op-text'>

<sup>Originally posted by **Flippo24** January  1, 2024</sup>
For me personally it would be nice if the FIFO method would be used to calculate the average price of the current position. Which in this situation would be 1.375 instead of 1.13. 

![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/8446dd4f-e141-443a-b65f-38567889489d)
</div>

**Comment by PaulSquires** [comment]
Thanks for the suggestion and information about how you use FIFO for your stocks. I will take all of that info into consideration when I implement the new functionality.

**Comment by PaulSquires** [comment]
I have just uploaded code to the repository with a first attempt at calculating the shares cost basis using FIFO.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/0f3a2706-a79c-45bd-a903-763c4451f5ed)

**Comment by Flippo24** [comment]
Thank you very much for the implementation. Fifo seems to be working properly.
I have entered share trades with the FIFO setting as a test and everything was fine. If I now switch back to AVG and restart, the share price is 0. If I switch back to FIFO, it is there again.

**Comment by PaulSquires** [comment]
> If I now switch back to AVG and restart, the share price is 0. 

I'll check into why this would happen and report back.

**Comment by Flippo24** [comment]
Your database works as expected. Mine does not. I have attached it for you.
[tt-database.zip](https://github.com/PaulSquires/TradeTracker/files/13906480/tt-database.zip)

**Comment by Flippo24** [comment]
The partial sales from my sample database are also not displayed under closed trades. They also do not appear in the 2024 statistics. They are included under transactions.
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/e8876a9c-bbb5-4dd9-8bb8-baa98ac664ae)

**Comment by PaulSquires** [comment]
The logic in the program is that as long as a trade is open, it is not counted as a "closed trade". So, for example, if you have an original trade set up as a 100 shares purchased and then sell 20, then the trade is still open with 80 shares remaining. 

Looks like this approach does not work well for "Trades" that have revolving purchases and sales that result in a trade never being closed. Kind of like the Wheel Strategy with Options - the trade could conceivably stay open forever.

Looks like another area that I will have to change in order to recognize revenue whenever a leg is fully closed rather than the trade itself.

**Comment by Flippo24** [comment]
That would definitely make sense for longer terms.

**Comment by Flippo24** [comment]
Good morning Paul, have you had time to take a look at my database? 
https://github.com/PaulSquires/TradeTracker/issues/20#issuecomment-1887634580

**Comment by PaulSquires** [comment]
Yes, I quickly tried it yesterday and indeed it does show zero so I need to look at the code today. Last night, my main development computer decided to start randomly shutting down so I can not use that machine until I fix it. I believe it was a Windows update because my Linux install on the dual boot works flawlessly (of course!). I am typing this using my laptop that also has a copy of my development system so I will use this laptop today to do some work on TradeTracker and I will post here once I fix the issues. Thanks!

**Comment by Flippo24** [comment]
Bad to hear that. Good that your sources are on Github.

**Comment by PaulSquires** [comment]
> Your database works as expected. Mine does not. I have attached it for you. [tt-database.zip](https://github.com/PaulSquires/TradeTracker/files/13906480/tt-database.zip)

Changes to source code implemented and uploaded to the repository.

Here is the Average Cost calculation based on the new code.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/93dda759-beff-4382-9ca2-89160d025788)

**Comment by PaulSquires** [comment]
> Bad to hear that. Good that your sources are on Github.

Yes, definitely! Using Github certainly makes dealing with code across multiple devices extremely easy. 👍

**Comment by PaulSquires** [comment]
I will close this issue now because the outstanding issues raised within this issue have been opened elsewhere in separately and will be addressed in those threads rather than here.

**Comment by PaulSquires** [comment]
Forgot to post this updated code commit before closing the issue:

> Added new Setting option and code logic to Exclude non-stock costs from costing calculation.

That functionality should now be active in the latest code upload.

**Comment by PaulSquires** [comment]
https://github.com/PaulSquires/TradeTracker/discussions/21#discussioncomment-8150401
