### ISSUE TITLE
Add Ticker in Other Income Expense

### ISSUE THREAD

**Issue by PaulSquires** [PaulSquires/TradeTracker#34]
### Discussed in https://github.com/PaulSquires/TradeTracker/discussions/33

<div type='discussions-op-text'>

<sup>Originally posted by **Flippo24** January 11, 2024</sup>
Can you add the ticker input field to Other Income Expense? Then there is the possibility to assign these amounts to a ticker.</div>

**Comment by PaulSquires** [comment]
Yes, this makes a lot of sense. This would allow you to create general income/expense that applies to your overall account, or have income/expense associated with specific tickers. I'll move this one over to Issues in order to track it.

**Comment by PaulSquires** [comment]
All done! (I hope). Modified source code uploaded to repository.

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/fdcc9f26-5ea0-46f3-93b8-aec3709582af)

![image](https://github.com/PaulSquires/TradeTracker/assets/14793592/5c4a9e06-ee0b-424d-9ac3-201f3edba70f)

**Comment by Flippo24** [comment]
Works as it should.
I thought I could write the dividends on the ticker without them appearing in the share price.

I wrote something for it in another [post](https://github.com/PaulSquires/TradeTracker/discussions/21#discussioncomment-8124454).

**Comment by PaulSquires** [comment]
> Works as it should. 

Excellent - thanks!

> I thought I could write the dividends on the ticker without them appearing in the share price.
> I wrote something for it in another [post](https://github.com/PaulSquires/TradeTracker/discussions/21#discussioncomment-8124454).

I will implement an additional Setting option to give the user the choice of including or excluding amounts other than the buys and sells into the share price.
