### ISSUE TITLE
Add box spread - leverage

### ISSUE THREAD

**Issue by andrewcz** [PaulSquires/TradeTracker#44]
hi @PaulSquires is the box spread be able to be added.

this is to lend and borrow money at better rates. 
-

similar to the below 

https://github.com/asemx/ibkrbox

**Comment by PaulSquires** [comment]
I looked at your link. That project attempts to automate the calculation for an optimal box spread: 

> (per the link) "This utility will automatically look up current treasury rates, and add .30 to get the yield rate. This will be used to calculate limit price. rate or limit price can be overridden as needed. It can also automatically calculate the right strikes and spread, with approximate expiry for given duration. All of these can be overridden as needed."

This type of functionality is beyond the scope of the TradeTracker project. TradeTracker is simply a tracker. Nothing more. It is not a trade builder, stock or option screener, or backtester. 

You can record a box spread in TradeTracker by choosing "Custom options Trade" and entering the 4 legs of the trade.

**Comment by PaulSquires** [comment]
Issue is beyond the scope of the TradeTracker application.
