### ISSUE TITLE
Show no stats if i have more than 1 option leg in position

### ISSUE THREAD

**Issue by tomaifauchai** [PaulSquires/TradeTracker#46]
![image](https://github.com/user-attachments/assets/289ce988-6568-48a1-8057-006e8db20920)

**Comment by PaulSquires** [comment]
That is odd. The only time I've seen that is when one or more parts of the leg information is incorrect. Example, the quantity, expiration date, strike price, or Put/Call. 

When you do a "Reconcile" does the resulting popup dialog give you any clues? (of course you need to be connected to TWS before doing the Reconcile).

**Comment by tomaifauchai** [comment]
Yeah i see weird stuff in reconcile. Like old out of date stuff. For example i dont have the TQQQ, SLV positions anymore and i see them there.
Also you can see i see 300 shares of SOXL locally, but in IBKR reconcile we only see 200. But i do have those in the account.

![image](https://github.com/user-attachments/assets/7c5b6394-0bbf-46f0-9623-7de40bc830bc)

**Comment by PaulSquires** [comment]
Maybe you meant to sell 3 covered calls for Nov 22 at 34.5 for the 300 shares that you have?

**Comment by tomaifauchai** [comment]
No here's what i have. 
![image](https://github.com/user-attachments/assets/0b5593cd-28cb-4e61-a90b-12e6c0ddb442)

**Comment by PaulSquires** [comment]
Thanks, yes, weird indeed. Looks like TradeTracker is pulling strange data. It requests all open positions from TWS so it is strange that it would receive positions that you no longer deem as being open.

I have a newer version of TradeTracker that I will post a link to for you shortly. You can install that version to see if it makes any difference. This would be the new cross platform version of TradeTracker that I have been working on.

Just make sure to backup your current TradeTracker data in case you need to reinstall it later (C:\Users\<username>\AppData\Local\TradeTracker), or the current application folder if you had originally installed the portable version.

**Comment by tomaifauchai** [comment]
Oh well, i restarted TradeTracker and now its fine.
Restarting IBKR didn't fixed it. I thought i would give it a shot...not sure what's going on tho.

![image](https://github.com/user-attachments/assets/4e9f53d1-6642-4953-9520-c1ef963abc0a)

**Comment by PaulSquires** [comment]
Here you go. Give this one a shot. You're the first person to see the new cross platform version so hopefully it works okay for you.

https://www.planetsquires.com/files/TradeTracker5-setup.msi

**Comment by tomaifauchai** [comment]
And thanks for the fast responses !

BTW i dont want to open a new ticket for that but: Is there a way i can run both a paper account and a live account with this? I don't want to try it, im wondering will it creates the database and stuff for the live account as well in that folder or i should run two "portable" version in a different folder ? Thanks

**Comment by PaulSquires** [comment]
You should run two different folders because the live & paper will overwrite the same database.

**Comment by PaulSquires** [comment]
Also, if you don't have a bug per se, you can always ask questions over in the Discussion forum.
https://github.com/PaulSquires/TradeTracker/discussions

**Comment by tomaifauchai** [comment]
Cool thanks, i'm setting this up in different folders now and new version looks pretty good too. Thanks for all the help.

**Comment by PaulSquires** [comment]
You are very welcome!  Happy that the new version is working well. If you run into any trouble then just let me know.
