### ISSUE TITLE
Error when trying to Buy to Close a futures trade

### ISSUE THREAD

**Issue by tomaifauchai** [PaulSquires/TradeTracker#47]
![image](https://github.com/user-attachments/assets/c65016d4-1735-4374-997d-54a385055ded)

Details: 
Sell to Open -1 ES
Buy to Close 1 ES

v5.00

**Comment by PaulSquires** [comment]
Hi, when setting up a futures trade you need to prefix the symbol with a forward slash. So, an ES contract should be originally bought as /ES.

**Comment by tomaifauchai** [comment]
Thanks, working!
![image](https://github.com/user-attachments/assets/21952c76-1be6-4442-84cd-1361bb9d3dfa)
