### ISSUE TITLE
Activate negative order fee in Trade Management

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#5]
Hey Paul,

Can you activate the entry of negative order fees in the Trade Management window? It sometimes happens when I sell options that I get a commission.

Thank you for your work. Nice program so far.

Regards Flippo

**Comment by PaulSquires** [comment]
Thanks Flippo for the suggestion. I have made the change to the Trade Management source code to allow negative Fee amounts. Seems to be working okay. The fix will be part of Version 4 which will released (hopefully) by the end of the first week in January 2024.

**Comment by Flippo24** [comment]
Thank you.

**Comment by PaulSquires** [comment]
You're very welcome. Happy to help. If you think of any other areas where the program can be improved then just let me know and I'll do my best to make it happen.
