### ISSUE TITLE
Could not save configuration file at first start

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#6]
At the first start, an error occurs when updating the configuration to version 4. If no configuration exists, it is created and saved at startup. It should then be changed to version 4 because the tt-config.txt file does not exist. This leads to the error when saving. This error also occurs when closing the program.

**Comment by PaulSquires** [comment]
Right you are. That is a regression that has occurred when I did some internal cleanup for the latest Version 4 preview. I will fix that and post a working Version 4 preview and then post here to let you know that it is fixed. Thanks for the bug report.

**Comment by PaulSquires** [comment]
This should now be fixed in the "TradeTracker.zip" download under the Preview-2 release.  https://github.com/PaulSquires/TradeTracker/releases/tag/4.0.0-preview2
The file is found when you expand the "Assets" section of that post.
Thanks.

**Comment by Flippo24** [comment]
Thank you very much. It now works exactly as it should. 

Have a nice New Year's night.
