### ISSUE TITLE
Trade duration incorrect after editing

### ISSUE THREAD

**Issue by Flippo24** [PaulSquires/TradeTracker#9]
I have entered a trade. But did not adjust the date of 31.12. when closing the trade. I changed the entry to the correct date afterwards, but the trade duration was not corrected.
![grafik](https://github.com/PaulSquires/TradeTracker/assets/5230426/43a2d2cf-d807-490e-9098-2f88e7e0cbcd)
The trade was closed on the day of opening.

**Comment by PaulSquires** [comment]
Thanks, I seem to be seeing the same as you and after I restarted the program the DIT returned to the correct 0 days. I must be missing a refresh calculation after the edit is processed.

**Comment by PaulSquires** [comment]
Added code to detect EDIT transaction and reload the correct dates. New TradeTracker.exe posted to the Preview-2 post under the "Assets" section. https://github.com/PaulSquires/TradeTracker/releases/tag/4.0.0-preview2
I will leave this issue open pending confirmation from you that this bug is fixed.

**Comment by Flippo24** [comment]
Happy New Year.
Thank you. The correct date is now displayed.
It is not a bug, but can you please correct the fact that when you are in the closed trades tab and edit an entry, you automatically jump to the active trades tab when saving.

**Comment by PaulSquires** [comment]
> ... can you please correct the fact that when you are in the closed trades tab and edit an entry, you automatically jump to the active trades tab when saving.

Happy New Year to you also! Yes, I will take a look at that today. Should be do-able.

**Comment by PaulSquires** [comment]
> > ... can you please correct the fact that when you are in the closed trades tab and edit an entry, you automatically jump to the active trades tab when saving.
> 
> Happy New Year to you also! Yes, I will take a look at that today. Should be do-able.

Actually, this was very easy to fix and is now corrected. Once I fix the "Missing Description" bug that you also reported then I will post a new EXE for you to try. Thanks for all of your help. It is VERY helpful having another person's perspective on using the program.

**Comment by Flippo24** [comment]
I know that. It is difficult to write a program that is suitable for all possible use cases. Especially if you only use it for a limited number of cases. In my case it is difficult for me to understand how the legs should be handled, because I use simple puts and calls. I am looking forward to your documentation. Also regarding the colors of the dots. 
I have very little idea about C++ so I can't provide a code help, but I would be happy to continue testing your beautiful tool and you fix the bugs. Win-win situation.  :laughing:
